// Mock data for Çanakkale Konut Rehberi (ÇKR)
// All content is placeholder/sample data for the frontend-only build.

export const brand = {
  name: 'Çanakkale Konut Rehberi',
  short: 'ÇKR',
  person: 'M. Kutay Öztürk',
  location: 'Çanakkale',
  tagline: 'İlan ezberiyle değil; piyasa gerçekleriyle konut kararı.',
};

export const navLinks = [
  { label: 'Piyasa Endeksi', href: '#piyasa' },
  { label: 'Rehber', href: '#rehber' },
  { label: 'Ben Kimim', href: '#ben-kimim' },
  { label: 'İhtiyaç Analizi', href: '#analiz' },
  { label: 'Danışmanlık', href: '#danismanlik' },
  { label: 'İletişim', href: '#iletisim' },
];

// Piyasa endeksi — 2025 Ocak'tan bugüne aylık işlenmiş veri seti.
export const marketMonths = [
  {
    id: 'ocak-2025',
    month: 'Ocak',
    year: '2025',
    status: 'Dengeli',
    statusNote: 'Piyasa temkinli ama dengeli ilerliyor',
    totalSales: '842',
    salesIpoteksiz: '694',
    salesIpotekli: '148',
    rentIncrease: '%55,80',
  },
  {
    id: 'subat-2025',
    month: 'Şubat',
    year: '2025',
    status: 'Dengeli',
    statusNote: 'Talep seçici, fiyatlar pazarlığa açık',
    totalSales: '876',
    salesIpoteksiz: '716',
    salesIpotekli: '160',
    rentIncrease: '%54,10',
  },
  {
    id: 'mart-2025',
    month: 'Mart',
    year: '2025',
    status: 'Canlanıyor',
    statusNote: 'Bahar talebiyle hareket artıyor',
    totalSales: '928',
    salesIpoteksiz: '751',
    salesIpotekli: '177',
    rentIncrease: '%52,60',
  },
  {
    id: 'nisan-2025',
    month: 'Nisan',
    year: '2025',
    status: 'Canlanıyor',
    statusNote: 'Alıcı ilgisi bölgesel olarak güçleniyor',
    totalSales: '981',
    salesIpoteksiz: '788',
    salesIpotekli: '193',
    rentIncrease: '%50,90',
  },
  {
    id: 'mayis-2025',
    month: 'Mayıs',
    year: '2025',
    status: 'Dengeli',
    statusNote: 'Satıcı beklentisi ile alıcı teklifi yakınlaşıyor',
    totalSales: '1014',
    salesIpoteksiz: '816',
    salesIpotekli: '198',
    rentIncrease: '%49,20',
  },
  {
    id: 'haziran-2025',
    month: 'Haziran',
    year: '2025',
    status: 'Dengeli',
    statusNote: 'Yaz etkisiyle kiralık talebi öne çıkıyor',
    totalSales: '1048',
    salesIpoteksiz: '839',
    salesIpotekli: '209',
    rentIncrease: '%47,80',
  },
  {
    id: 'temmuz-2025',
    month: 'Temmuz',
    year: '2025',
    status: 'Seçici Talep',
    statusNote: 'Alıcılar fiyat/konum dengesine daha hassas',
    totalSales: '1067',
    salesIpoteksiz: '852',
    salesIpotekli: '215',
    rentIncrease: '%46,40',
  },
  {
    id: 'agustos-2025',
    month: 'Ağustos',
    year: '2025',
    status: 'Seçici Talep',
    statusNote: 'Doğru fiyatlanan mülkler daha hızlı ayrışıyor',
    totalSales: '1092',
    salesIpoteksiz: '870',
    salesIpotekli: '222',
    rentIncrease: '%45,10',
  },
  {
    id: 'eylul-2025',
    month: 'Eylül',
    year: '2025',
    status: 'Dengeli',
    statusNote: 'Okul dönemiyle merkez talebi yeniden belirgin',
    totalSales: '1125',
    salesIpoteksiz: '895',
    salesIpotekli: '230',
    rentIncrease: '%43,70',
  },
  {
    id: 'ekim-2025',
    month: 'Ekim',
    year: '2025',
    status: 'Alıcıya Dönüyor',
    statusNote: 'Pazarlık payı yükseliyor',
    totalSales: '1108',
    salesIpoteksiz: '884',
    salesIpotekli: '224',
    rentIncrease: '%42,30',
  },
  {
    id: 'kasim-2025',
    month: 'Kasım',
    year: '2025',
    status: 'Alıcıya Dönüyor',
    statusNote: 'Bekleyen ilanlarda fiyat revizyonu ihtiyacı artıyor',
    totalSales: '1084',
    salesIpoteksiz: '864',
    salesIpotekli: '220',
    rentIncrease: '%40,90',
  },
  {
    id: 'aralik-2025',
    month: 'Aralık',
    year: '2025',
    status: 'Alıcı Lehine',
    statusNote: 'Yıl sonu kararlarında gerçekçi fiyat avantaj sağlıyor',
    totalSales: '1059',
    salesIpoteksiz: '846',
    salesIpotekli: '213',
    rentIncrease: '%39,60',
  },
  {
    id: 'ocak-2026',
    month: 'Ocak',
    year: '2026',
    status: 'Alıcı Lehine',
    statusNote: 'Talep var ama fiyat seçiciliği yüksek',
    totalSales: '1018',
    salesIpoteksiz: '814',
    salesIpotekli: '204',
    rentIncrease: '%38,20',
  },
  {
    id: 'subat-2026',
    month: 'Şubat',
    year: '2026',
    status: 'Alıcı Lehine',
    statusNote: 'Nakit alıcı pazarlıkta daha güçlü',
    totalSales: '1036',
    salesIpoteksiz: '828',
    salesIpotekli: '208',
    rentIncrease: '%36,90',
  },
  {
    id: 'mart-2026',
    month: 'Mart',
    year: '2026',
    status: 'Dengeleniyor',
    statusNote: 'Talep yeniden ölçülü şekilde canlanıyor',
    totalSales: '1079',
    salesIpoteksiz: '858',
    salesIpotekli: '221',
    rentIncrease: '%35,50',
  },
  {
    id: 'nisan-2026',
    month: 'Nisan',
    year: '2026',
    status: 'Dengeleniyor',
    statusNote: 'Doğru fiyatlı portföylerde görüşme artıyor',
    totalSales: '1116',
    salesIpoteksiz: '886',
    salesIpotekli: '230',
    rentIncrease: '%34,20',
  },
  {
    id: 'mayis-2026',
    month: 'Mayıs',
    year: '2026',
    status: 'Dengeli',
    statusNote: 'Alıcı ve satıcı beklentisi daha okunabilir',
    totalSales: '1138',
    salesIpoteksiz: '906',
    salesIpotekli: '232',
    rentIncrease: '%33,10',
  },
  {
    id: 'haziran-2026',
    month: 'Haziran',
    year: '2026',
    status: 'Dengeli',
    statusNote: 'Piyasa alıcı ve satıcı arasında dengeli',
    totalSales: '1120',
    salesIpoteksiz: '905',
    salesIpotekli: '215',
    rentIncrease: '%32,40',
  },
  {
    id: 'temmuz-2026',
    month: 'Temmuz',
    year: '2026',
    status: 'Alıcıya Dönüyor',
    statusNote: 'Talep yavaşlıyor, piyasa alıcı lehine dönüyor',
    totalSales: '1185',
    salesIpoteksiz: '960',
    salesIpotekli: '225',
    rentIncrease: '%31,85',
  },
  {
    id: 'agustos-2026',
    month: 'Ağustos',
    year: '2026',
    status: 'Alıcı Lehine',
    statusNote: 'Piyasa şu an alıcı lehine',
    totalSales: '1248',
    salesIpoteksiz: '1018',
    salesIpotekli: '230',
    rentIncrease: '%31,79',
  },
  {
    id: 'eylul-2026',
    month: 'Eylül',
    year: '2026',
    status: 'Alıcı Lehine',
    statusNote: 'Gerçekçi fiyatlanan mülkler daha görünür',
    totalSales: '1216',
    salesIpoteksiz: '994',
    salesIpotekli: '222',
    rentIncrease: '%30,90',
  },
  {
    id: 'ekim-2026',
    month: 'Ekim',
    year: '2026',
    status: 'Seçici Piyasa',
    statusNote: 'Son veriler alıcının daha seçici davrandığını gösteriyor',
    totalSales: '1194',
    salesIpoteksiz: '981',
    salesIpotekli: '213',
    rentIncrease: '%30,20',
  },
];

export const testimonials = [
  {
    name: 'Ayşe K.',
    role: 'Alıcı',
    text: 'İlan fiyatlarına takılıp kalmıştım. Kutay Bey satılabilir fiyatın ne olduğunu net anlattı, doğru bütçeyle doğru evi aldık.',
  },
  {
    name: 'Mehmet D.',
    role: 'Satıcı',
    text: 'Evimi aylarca satamadım. ÇKR ile gerçekçi fiyatı konuşunca iki haftada ciddi alıcı buldum. Ezber değil, veri konuştu.',
  },
  {
    name: 'Selin A.',
    role: 'Kiraya Veren',
    text: 'Kira potansiyelini gerçek piyasaya göre belirledik. Boş kalma riskini azaltan net bir yol haritası çıkardı.',
  },
  {
    name: 'Onur T.',
    role: 'Kiracı',
    text: 'Bütçeme ve ihtiyacıma göre bölge önerisi aldım. Acele ettirmeden, doğru soruları sorarak karar vermemi sağladı.',
  },
];

export const blogPosts = [
  {
    title: 'İlan fiyatı ile satılabilir fiyat neden aynı değildir?',
    excerpt: 'İlanda yazan rakam bir temennidir. Satılabilir fiyat ise alıcının gerçekten ilgi gösterdiği, teklif verdiği seviyedir.',
    tag: 'Satıcı Rehberi',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzV8MHwxfHNlYXJjaHwzfHxhcGFydG1lbnQlMjBpbnRlcmlvcnxlbnwwfHx8fDE3OTEyOTA2NjJ8MA&ixlib=rb-4.1.0&q=85',
    read: '7 dk',
    content: [
      { type: 'p', text: `İlan sitelerine giriyorsunuz. Sizin evinize benzeyen dairelerin fiyatlarına bakıyorsunuz. 10 milyon, 10 milyon 500 bin, 11 milyon... Doğal olarak şöyle düşünüyorsunuz: "Benim evimin bunlardan ne eksiği var? O zaman benim evim de en az 10 milyon eder." Mantıklı görünüyor, değil mi?` },
      { type: 'quote', text: `Ama burada çok önemli bir şeyi gözden kaçırıyorsunuz: O evlerin 10 milyon liraya satılık olması, 10 milyon lira ettiği anlamına gelmiyor. Hatta o fiyatlara satılabilecekleri anlamına bile gelmiyor.` },
      { type: 'h2', text: 'İlan siteleri size piyasanın yalnızca yarısını gösterir' },
      { type: 'p', text: `İlan sitelerinde gördüğünüz rakamlar, mülk sahiplerinin evleri için talep ettiği fiyatlardır. Peki görmediğiniz taraf? O evler ne kadar süredir satılık, kaç kişi aradı, kaç kişi evi görmeye gitti, alıcılar ne kadar teklif verdi ve gerçekten satılanlar kaça satıldı?` },
      { type: 'p', text: `Belki 10 milyon isteyen evin sahibi altı aydır tek bir ciddi teklif bile almadı. Belki 9 milyon isteyen başka bir ev, iki haftada 8 milyon 500 bin liraya satıldı. Şimdi hangisi sizin eviniz için daha anlamlı bir emsal? Satılmayan evin istenen fiyatı mı, satılmış evin gerçekleşen fiyatı mı?` },
      { type: 'h2', text: 'Alıcı sizin evinizi tek başına değerlendirmez' },
      { type: 'p', text: `Diyelim ki eviniz için 10 milyon lira istiyorsunuz. Alıcının ise 10 milyon liralık bütçesi var. Bu bütçeyle sizin evinizi, aynı bölgedeki daha yeni bir binayı, biraz daha uzaktaki daha büyük bir daireyi ve belki de farklı bir sitedeki evi inceleyebiliyor.` },
      { type: 'quote', text: `Evinizin kaç para etmesini istediğiniz değil, alıcının neden o parayı ödemeye razı olacağı önemlidir.` },
      { type: 'h2', text: 'Peki doğru fiyat nasıl bulunur?' },
      { type: 'p', text: `Doğru fiyat, yalnızca çevredeki ilanların ortalaması alınarak bulunmaz. Ulaşılabilen gerçekleşmiş satışlar incelenir. Benzer özelliklerdeki mülklerin ne kadar sürede ve hangi koşullarda satıldığı değerlendirilir. Mevcut rakipler, alıcıların tercihleri ve gelen teklifler birlikte okunur.` },
      { type: 'p', text: `Binanın yaşı, yapısal özellikleri, konumu, katı, cephesi, kullanım alanı ve sunduğu avantajlar elbette önemlidir. Ama bunların her birinin parasal karşılığı, alıcının o özelliklere ne kadar değer verdiğiyle ilişkilidir.` },
      { type: 'h2', text: 'Yüksek fiyatla başlayıp sonra düşürsek olmaz mı?' },
      { type: 'p', text: `Olur. Ama bunun da bir maliyeti olabilir. Bir ilan ilk yayınlandığında, bölgede zaten ev arayan alıcıların dikkatini çekme fırsatı yakalar. Bu kişiler uzun süredir piyasayı takip ettikleri için alternatifleri tanırlar. Eviniz bu alıcılara pahalı gelirse, ilanınızı görüp geçebilirler.` },
      { type: 'p', text: `Aylar sonra fiyatı düşürmeniz, ilk günkü ilgiyi mutlaka geri getirmez. Elbette her satılmayan evin sorunu fiyat değildir. Kötü fotoğraflar, eksik bilgiler, yanlış hedef kitle veya yetersiz pazarlama da satışın önünde engel olabilir. Ama iyi pazarlama, yanlış fiyatı doğru fiyata dönüştürmez.` },
      { type: 'h2', text: 'Sonuç olarak' },
      { type: 'p', text: `Mülkünüzü istediğiniz fiyattan satışa çıkarmakta özgürsünüz. Fakat bir fiyatı istemekle, o fiyatı ödemeye hazır bir alıcı bulmak aynı şey değildir. Benim değerleme yaklaşımım da tam olarak bu ayrım üzerine kurulu.` },
      { type: 'quote', text: `Bir evin değerini doğru bilmek, onu ucuza satmak değil; neyi, neden ve kaça sattığınızı bilmektir.` },
    ],
  },
  {
    title: 'Alıcı piyasasında fiyatı kim belirler?',
    excerpt: 'Alıcı piyasasında fiyatı satıcının beklentisi değil, talebin yoğunluğu belirler. Doğru okunduğunda avantaja dönüşür.',
    tag: 'Alıcı Rehberi',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzZ8MHwxfHNlYXJjaHwxfHxob3VzZSUyMGtleXN8ZW58MHx8fHwxNzkxMjkwNjYyfDA&ixlib=rb-4.1.0&q=85',
    read: '6 dk',
    content: [
      { type: 'p', text: `Bir evin fiyatını kim belirler? Mal sahibi mi? Emlakçı mı? Yoksa ilan sitesindeki diğer evlerin fiyatları mı? Aslında hiçbiri tek başına belirlemez.` },
      { type: 'quote', text: `Bir mülkün piyasa değerini, o mülke para ödemeye hazır alıcıların tercihleri şekillendirir.` },
      { type: 'h2', text: 'Alıcı neden piyasayı daha iyi bilir?' },
      { type: 'p', text: `Çünkü bir süredir ev arıyordur. Belki haftalardır ilan inceliyor, farklı mahallelerde ev geziyor, emlakçılarla konuşuyor, teklif veriyor. 10 milyon lira istenen evin 9 milyona bırakılabileceğini, 8 milyonluk başka bir evin neden hâlâ satılmadığını öğreniyor.` },
      { type: 'p', text: `Hangi sitede aidatın yüksek olduğunu, hangi binada otopark bulunmadığını, hangi evin fotoğraflarda göründüğünden küçük olduğunu bizzat görüyor. Kısacası yalnızca ilan fiyatlarını değil, o fiyatların arkasındaki gerçekleri de öğrenmeye başlıyor.` },
      { type: 'h2', text: 'Alıcı neye para verir?' },
      { type: 'p', text: `Satıcı evini anlatırken genellikle sahip olduğu özellikleri sıralar. Güney cephe, geniş balkon, kaliteli mutfak, merkezi konum... Bunların hepsi değerli olabilir. Ama alıcının aradığı şey bunlardan farklıysa?` },
      { type: 'quote', text: `Bir özelliğin bulunması başka şeydir, alıcının o özellik için fazladan para ödemeye istekli olması başka şeydir.` },
      { type: 'h2', text: 'Her düşük teklif evinizin değerini göstermez' },
      { type: 'p', text: `Bir alıcının evinize 7 milyon lira teklif etmesi, evinizin mutlaka 7 milyon ettiği anlamına gelmez. Alıcı da mümkün olan en avantajlı fiyatı yakalamaya çalışıyor olabilir. Önemli olan tek bir teklif değil, piyasadan gelen işaretlerin bütünüdür.` },
      { type: 'p', text: `Benzer özelliklerdeki mülkler hangi fiyatlardan satılıyor? Sizin evinize ne kadar ilgi var? Gerçekten satın alma gücü bulunan alıcılar hangi aralıkta teklif veriyor? Birden fazla ciddi alıcı birbirine yakın rakamlar öneriyorsa, bu dikkate alınması gereken güçlü bir piyasa verisidir.` },
      { type: 'h2', text: 'Satıcının rolü ne?' },
      { type: 'p', text: `Alıcı piyasa değerinin oluşmasında belirleyicidir. Ama satışın gerçekleşmesi için satıcının da o bedeli kabul etmesi gerekir. Satıcı, mevcut fiyatlardan satmak istemeyebilir. Beklemeyi tercih edebilir. Bu onun hakkıdır.` },
      { type: 'p', text: `Ancak beklemeyi tercih etmekle, mülkün bugünkü piyasa değerinin daha yüksek olduğunu iddia etmek aynı şey değildir. Piyasa bugün beklediğiniz fiyatı vermiyor olabilir. Gelecekte verebilir de, vermeyebilir de. Bu bir beklentidir. Gerçekleşmiş bir değer değildir.` },
      { type: 'h2', text: 'Peki emlakçı ne yapar?' },
      { type: 'p', text: `Bana göre emlakçının asıl işi, satıcıyı yüksek fiyatla mutlu etmek veya alıcıyı bir an önce satın almaya ikna etmek değildir. Emlakçılık biraz iz sürmeye benzer.` },
      { type: 'p', text: `Alıcı ne arıyor? Hangi mülkleri karşılaştırıyor? Neyi beğenmiyor? Hangi özellik için daha fazla ödemeye razı oluyor? Bu soruların cevaplarını takip eder, topladığınız bilgiyi doğru yorumlarsanız mülkün piyasadaki yerini çok daha sağlıklı görebilirsiniz.` },
      { type: 'quote', text: `Benim fikrim bu değil. Piyasanın bize gösterdiği tablo bu.` },
    ],
  },
  {
    title: 'Çanakkale\'de bölge seçimi: bütçe mi, yaşam mı?',
    excerpt: 'Doğru bölge; sadece fiyatla değil, ulaşım, kira potansiyeli ve uzun vadeli değer artışıyla birlikte değerlendirilmelidir.',
    tag: 'Bölge Rehberi',
    image: 'https://images.unsplash.com/photo-1448630360428-65456885c650?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzV8MHwxfHNlYXJjaHw0fHxyZXNpZGVudGlhbCUyMGJ1aWxkaW5nfGVufDB8fHx8MTc5MTI5MDY2Mnww&ixlib=rb-4.1.0&q=85',
    read: '8 dk',
    content: [
      { type: 'p', text: `Çanakkale'de ev almak isteyen birinin ilk sorusu genellikle şu oluyor: "Şu kadar param var. Hangi mahalleden ev almalıyım?" Ben ise önce başka bir şey sormayı tercih ediyorum: "Nasıl bir hayat yaşamak istiyorsunuz?"` },
      { type: 'p', text: `Çünkü aynı bütçeyle farklı bölgelerde birbirinden çok farklı evler alabilirsiniz. Ama mesele yalnızca ne kadar büyük veya yeni bir ev alabildiğiniz değil. O evde nasıl yaşayacağınız.` },
      { type: 'h2', text: 'İyi bölge diye bir şey var mı?' },
      { type: 'p', text: `Elbette bazı bölgelerin diğerlerine göre avantajları var. Ama herkes için en iyi olan tek bir mahalle yok. Esenler'de bir site dairesi, Kepez'de bir apartman dairesi, Barbaros'ta merkezi bir konut veya Güzelyalı'da müstakil bir ev birbirinin doğrudan alternatifi olmak zorunda değil.` },
      { type: 'p', text: `Bir alıcı site içinde düzenli bir yaşam, otopark ve ortak kullanım alanları ararken, başka biri markete, okula ve işine yürüyerek ulaşabilmeyi önemseyebilir. Bir başkası içinse kalabalıktan uzaklaşmak, bahçesinde zaman geçirmek veya denize yakın olmak çok daha değerlidir.` },
      { type: 'h2', text: 'Bütçe sizi bir bölgeye mahkûm etmemeli' },
      { type: 'p', text: `Konut ararken yapılan önemli hatalardan biri, önce bir mahalle belirleyip bütün alternatifleri orada aramaktır. Diyelim ki 6 milyon liralık bütçeniz var. İstediğiniz bölgede bu paraya daha eski, küçük ve masraf gerektiren bir daire bulabiliyorsunuz. Biraz farklı bir bölgede ise daha yeni, daha geniş veya ihtiyaçlarınıza daha uygun bir konut seçeneği var.` },
      { type: 'quote', text: `Ev alırken yalnızca bir yapı satın almıyorsunuz. Günlük hayatınızın önemli bir bölümünü de seçiyorsunuz.` },
      { type: 'h2', text: 'Satın alma fiyatı tek maliyet değildir' },
      { type: 'p', text: `İki evin fiyatı aynı olabilir. Ama size yaşatacağı maliyet aynı olmayabilir. Daha uzak bir bölgede aldığınız ev, her gün daha fazla ulaşım masrafı ve zaman kaybı anlamına gelebilir. Bir sitede ortak alanların sağladığı konfor, yüksek aidat giderleriyle birlikte gelebilir.` },
      { type: 'p', text: `Çanakkale'de deprem ve zemin konusu da konut tercihinde önemli bir yer tutuyor. Ancak bir mahalleyi bütünüyle güvenli veya güvensiz ilan etmek doğru değil. Zemin koşulları parsel bazında değişebilir. Binanın taşıyıcı sistemi, projelendirilmesi, yapım kalitesi ve mevcut durumu ayrıca değerlendirilmelidir.` },
      { type: 'quote', text: `Mahallenin adını bilmek, binanın güvenliğini bildiğiniz anlamına gelmez.` },
      { type: 'h2', text: 'Aynı mahallede iki sokak bile aynı değil' },
      { type: 'p', text: `Bir mahalleyi beğenmiş olabilirsiniz. Ama bu, o mahalledeki her evin sizin için uygun olduğu anlamına gelmez. Sokağın araç trafiği, park imkânları, çevredeki yapılaşma, güneş alma durumu, gürültü ve günlük ihtiyaçlara ulaşım gibi konular yaşam kalitenizi doğrudan etkiler.` },
      { type: 'h2', text: 'Yatırım için ev alıyorsanız denklem değişir' },
      { type: 'p', text: `Oturmak için ev almakla yatırım için ev almak aynı şey değil. Kendi oturacağınız evde yaşam konforunuz daha ön planda olabilir. Yatırım amaçlı aldığınız bir evde ise kiracı talebi, beklenen kira geliri, aidat, boş kalma riski ve ileride yeniden satılabilme potansiyeli daha fazla önem kazanır.` },
      { type: 'h2', text: 'Peki nereden başlamalı?' },
      { type: 'p', text: `Bana göre önce haritayı değil, günlük hayatınızı incelemelisiniz. İşiniz nerede? Çocuğunuzun okulu nerede? Arabanız var mı? Evinizde ne kadar zaman geçiriyorsunuz? Sosyal yaşamınızdan ne bekliyorsunuz? Önümüzdeki beş yılda hayatınızın nasıl değişmesini öngörüyorsunuz?` },
      { type: 'quote', text: `En pahalı mahalle, en doğru mahalle değildir. En ucuz ev de her zaman en avantajlı ev değildir.` },
      { type: 'p', text: `Çanakkale'de nereden ev alınır sorusunun herkese verebileceğim tek bir cevabı yok. Ama doğru soruları sorarsak, sizin için hangi bölgenin daha uygun olduğunu birlikte bulabiliriz.` },
    ],
  },
];

export const consultancySteps = [
  {
    no: '01',
    title: 'İhtiyaç Analizi',
    desc: 'Alıcı, satıcı, kiracı veya kiraya veren olarak hedefinizi, bütçenizi ve beklentinizi netleştiriyoruz.',
  },
  {
    no: '02',
    title: 'Piyasa Okuması',
    desc: 'Bölge, satılabilir fiyat ve kira potansiyelini güncel ÇKR verileriyle birlikte değerlendiriyoruz.',
  },
  {
    no: '03',
    title: 'Karar Zemini',
    desc: 'İlan ezberi yerine; gerçeklerle beslenen, size özel bir karar zemini oluşturuyoruz.',
  },
  {
    no: '04',
    title: 'Yönlendirme',
    desc: 'Sürecin her adımında, doğru zamanda doğru hamleyi yapmanız için yanınızda oluyoruz.',
  },
];

export const aboutText = {
  portrait: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
  paragraphs: [
    'Merhaba, ben M. Kutay Öztürk. Çanakkale\'de alıcı, satıcı, kiracı ve kiraya verenlere; ilan ezberiyle değil, piyasa gerçekleriyle karar rehberliği sunuyorum.',
    'Benim işim size ev beğendirmek değil; doğru soruları sorarak, bütçeniz ve ihtiyacınızla örtüşen sağlam bir karar zemini oluşturmak. İlan fiyatı ile satılabilir fiyat arasındaki farkı net göstermek, bu işin özüdür.',
    'ÇKR; bölge, bütçe, satılabilir fiyat ve kira potansiyelini birlikte okur. Böylece acele değil, bilinçli kararlar verirsiniz.',
  ],
  highlights: [
    { value: '12+', label: 'Yıl saha tecrübesi' },
    { value: '%100', label: 'Gerçek piyasa verisi' },
    { value: 'Çanakkale', label: 'Odaklı bölge uzmanlığı' },
  ],
};

// Melis asistan — kural tabanlı akış
export const melis = {
  name: 'Melis',
  role: 'ÇKR Dijital Asistanı',
  greeting: 'Merhaba, ben Melis. Size doğru yönlendirmeyi yapabilmem için durumunuzu seçer misiniz?',
  disclaimer: 'Melis, ÇKR\'nin dijital yardımcı asistanıdır.',
  options: [
    { key: 'alici', label: 'Ev almak istiyorum', target: 'alici', reply: 'Harika! Doğru evi doğru fiyata bulmak için kısa bir Alıcı İhtiyaç Analizi yapalım. Formu sizin için açıyorum.' },
    { key: 'satici', label: 'Evimi satmak istiyorum', target: 'satici', reply: 'Satılabilir fiyatı net konuşalım. Satıcı İhtiyaç Analizi formunu açıyorum, birkaç soruyla başlıyoruz.' },
    { key: 'kiraya-veren', label: 'Evimi kiraya vermek istiyorum', target: 'kiraya-veren', reply: 'Kira potansiyelinizi gerçek piyasaya göre belirleyelim. Kiraya Veren analizini açıyorum.' },
    { key: 'kiralayan', label: 'Kiralık ev arıyorum', target: 'kiralayan', reply: 'Bütçe ve ihtiyacınıza göre bölge önerelim. Kiralayan İhtiyaç Analizini açıyorum.' },
  ],
};
